config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root to: "tasks#index"
  resources :tasks
  get '/tasks/:id/assign', to: 'tasks#assign',as: :assign_task
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user
    enum status: {backlog: 0, wip: 1, closed:2}

    with_options presence: true do
        validates :title
        validates :content
        validates :deadline
        validates :status
    end

    paginates_per 10

    scope :index_all, -> {
        where.not(status: :closed)
        .select(:id, :title, :content, :deadline, :status, :user_id)
        .order(created_at: :desc)
        .includes(:user)
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :tasks

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_task, only: [:show, :destroy, :edit, :update, :assign]
  before_action :move_to_index, only: [:edit, :update, :assign, :destroy]

  def index
    @tasks = Task.index_all.page(params[:page]).per(6)
  end

  def new
    @task = Task.new
  end

  def show
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
        redirect_to task_path
    else
        render :edit
    end
  end

  def destroy
    if current_user.id != @task.user.id
      raise "実行時エラーです"
    end
		@task.destroy
    redirect_to root_path
  end

  def assign
  end

  private

  def task_params
    params.require(:task).permit(:title, :content, :deadline, :status, :user_id)
  end

  def set_task
    @task = Task.find(params[:id])
  end

  def move_to_index
    redirect_to root_path if current_user.id !=  @task.user.id
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @tasks = Task.where(user_id: current_user.id, status: [:backlog,:wip]).page(params[:page]).per(6)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4">
    <%= link_to "タスク管理アプリ",root_path, class: "navbar-brand"%>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse" >
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "タスク一覧", root_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
        <%if user_signed_in?%>
          <%= link_to "マイタスク", user_path(current_user.id), class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "ユーザー設定", edit_user_registration_path, class: "nav-link", tabindex: "-1"%>
        </li>
        <% end %>
      </ul>
      <div class="mt-2 mt-md-0 d-flex">
        <%if user_signed_in? %>
          <p class="mt-2">ようこそ<%= current_user.name%>さん</p>
          <%= link_to "サインアウト", destroy_user_session_path, method: :delete, class: "nav-link", tabiindex: "-1",data: { confirm: '本当にログアウトしますか?' } %>
        <% else %>
          <%= link_to "サインアップ", new_user_registration_path, tabindex: "-1", class: "nav-link" %>
          <%= link_to "ログイン", new_user_session_path, tabindex: "-1", class: "nav-link" %>
        <% end %>
      </div>
    </div>
  </nav>
  <% if flash[:notice] %>
    <% flash.each do |message_type, message|%>
      <%= content_tag :div, message, class: "alert alert-success"%>
    <% end %>
  <% else %>
    <% flash.each do |message_type, message|%>
      <%= content_tag :div, message, class: "alert alert-danger"%>
    <% end %>
  <% end %>

    <%= yield %>
  </body>
</html>

app/views/shared/_error.html.erb
<% if model.errors.any? %>
<div class="alert alert-danger" role="alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_form.html.erb
<%= form_with model: @task, local: true do |f| %>
<%= render 'shared/error', model: f.object %>
  <div class="field mt-2">
    <%= f.label :title, "タイトル" %>
    <%= f.text_field :title, class: "form-control"%>
  </div>
  <div class="field mt-2">
    <%= f.label :content, "内容" %>
    <%= f.text_area :content, class: "form-control"%>
  </div>
  <div class="field mt-2">
    <%= f.label :deadline, "締め切り" %><br>
    <%= f.datetime_select :deadline,{},class: "form-control bootstrap-date"%>
  </div>
  <div class="field mt-2">
    <%= f.label :status, "ステータス" %><br>

      <%= f.radio_button :status, :backlog %>
      <%= f.label :status_backlog, '未対応' %>

      <%= f.radio_button :status, :wip %>
      <%= f.label :status_wip, '対応中' %>

    <% if params[:action] == "edit" %>
      <%= f.radio_button :status, :closed %>
      <%= f.label :status_closed, '完了' %>
    <% end %>
  </div>
  <%= f.hidden_field :user_id, value: current_user.id%>

  <% if params[:action] == "edit" %>
    <%= f.submit '更新する', class: 'btn btn-success' %>
  <% else %>
    <%= f.submit '作成する', class: 'btn btn-success' %>
  <% end %>

  <%= link_to "一覧へ戻る", root_path, class:"btn btn-light"%>
<% end %>

app/views/shared/_task.html.erb
<div class = "col-xs-12 col-md-6 mb-5">
  <% if Time.now <= task.deadline %>
  <div class="card border-success" >
    <div class="card-header bg-success"><%= task.title %></div>
  <% else %>
  <div class="card border-danger" >
    <div class="card-header bg-danger"><%= task.title %></div>
  <% end %>
    <div class="card-body">
      <p class="card-text"><%= task.content%></p>
      <p class= "card-text">期限：<%= task.deadline.to_s(:datetime_jp)%></p>
      <p>担当者：<%= task.user.name %></p>
      <p>ステータス：<%= task.status_i18n%></p>
      <%= link_to "詳細",task_path(task.id), class: "btn btn-light"%>
    <% if user_signed_in? && task.user.id == current_user.id%>
      <%= link_to "編集",edit_task_path(task.id), class: "btn btn-info"%>
      <%= link_to "削除",task_path(task.id), class: "btn btn-danger", method: :delete%>
    <% end %>
    </div>
  </div>
</div>

app/views/tasks/assign.html.erb
<div class="container">
  <div class ="field">
    <%= form_with model: @task, local: true do |f|%>
      <div class= "d-flex justify-content-lg-between">
        <div>
          <p>現在アサインされているユーザー</p>
          <p><%= @task.user.name %></p>
        </div>
        <div>
          <p>新しくアサインするユーザー</p>
          <%= f.collection_select(:user_id, User.where.not(id: current_user.id), :id, :name, {}, {class: "form-control"}) %>
          <%= f.hidden_field :title, value: @task.title%>
          <%= f.hidden_field :content, value: @task.content%>
          <%= f.hidden_field :deadline, value: @task.deadline%>
          <%= f.hidden_field :status, value: @task.status%>
        </div>
      </div>
      <%= f.submit 'アサインする', class: 'btn btn-success' %>
    <% end %>
  </div>
  <div class="jumbotron mt-3">
    <h1 class="display-4"><%= @task.title%></h1>
		<p><%= @task.content %></p>
    <p>期限：<%= @task.deadline.to_s(:datetime_jp)%></p>
    <p>ステータス：<%= @task.status_i18n%></p>
  </div>
</div>

app/views/tasks/edit.html.erb
<div class="container">
  <h1>タスク編集</h1>
  <%= render partial: "shared/form" %>
</div>

app/views/tasks/index.html.erb
<div class = "container">
  <h1>タスク一覧</h1>
  <%= link_to "タスク新規作成", new_task_path, class: "btn btn-light"%>
  <div class = "row">
    <%= render partial: 'shared/task', collection: @tasks%>
    <%= paginate @tasks %>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <h1>タスク作成</h1>
  <%= render partial: "shared/form" %>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <div class="jumbotron">
    <h1 class="display-4"><%= @task.title%></h1>
    <p><%= @task.content %></p>
    <p>期限：<%= @task.deadline.to_s(:datetime_jp)%></p>
    <p>担当者： <%= @task.user.name%></p>
    <p>ステータス：<%= @task.status_i18n%></p>
    <%= link_to "一覧へ戻る", root_path, class: "btn btn-light"%>
    <% if user_signed_in?  && current_user.id == @task.user.id %>
      <%= link_to "編集", edit_task_path(@task.id), class: "btn btn-info"%>
      <%= link_to "アサイン", assign_task_path, class: "btn btn-success"%>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class = "container">
  <h1>マイタスク</h1>
  <%= link_to "タスク新規作成", new_task_path, class: "btn btn-light"%>
  <div class = "row">
    <%= render partial: 'shared/task', collection: @tasks%>
    <%= paginate @tasks %>
  </div>
</div>